<?php
// $Id$

function bbcode_help($section) {
  if ($section == "admin/modules#description") {
    return t("Allow the use of bbcode in your posts.");
  }
}

function bbcode_filter_tips($delta, $format, $long = false) {
  if ($long) {
    include_once 'bbcode-help.inc';
    return _bbcode_filter_tip();
  }
  else {
    return t("You can use <a href=\"%bbcode_help\">BBCode tags</a> in the text, URLs will be automatically converted to links", array("%bbcode_help" => url("filter/tips/$format", NULL, 'filter-bbcode')));
  }
}

function bbcode_filter($op, $delta = 0, $format = -1, $text = '') {
  switch ($op) {
    case 'list':
      return array(0 => t('BBCode'));

    case 'description':
      return t('Converts BBCode to html.');

    case 'process':
      include_once 'bbcode-filter.inc';
      return _bbcode_filter_process($text, $format);

    case 'settings':
      $form = array();
      $form['bbcode_filter'] = array(
        '#type' => 'fieldset', 
        '#title' => t('BBCode filter'), 
        '#collapsible' => TRUE, 
        '#collapsed' => TRUE);
      $form['bbcode_filter']["bbcode_encode_mailto_$format"] = array(
        '#type' => 'select', 
        '#title' => t('Email address encoding'), 
        '#default_value' => variable_get("bbcode_encode_mailto_$format", 'match'), 
        '#options' => array(t("Disabled"), t("Enabled")), 
        '#description' => t('Whether to encode email addresses with javascript. With this method you will have clickable mailto links, but it will be a bit harder for spam robots to collect them.'));
      return $form;

    default:
      return $text;
  }
}
